### ISSUE TITLE
Make systemd user services aware of env variables which hold passwords?

### ISSUE THREAD

**Issue by doronbehar** [cruegge/pam-gnupg#2]
Hello, I'm not totally sure what I try to do is possible but I could really use some help here.

Here's my setup:

I have a password protected MPD server and I store it's password with [`pass`](https://www.passwordstore.org/).

I have this line in my `~/.zshenv`:
```zsh
export MPD_HOST="$(pass software/mpd)@localhost"
```
In addition, I installed [mpDris2](https://github.com/eonpatapon/mpDris2) which provides a user systemd service that connects to `$MPD_HOST` and it needs the password to be fully functional.

At the current setup, the systemd service of mpDris2 is not aware of `$MPD_HOST` which is set up in `~/.zshenv`. In contrast, if I run `mpDris2` in a terminal, it works just fine because it knows.

According to these tests, I need to make `mpDris2.service` be aware of `$MPD_HOST` after it was evaluated with `pass`. I know I could `systemctl --user edit mpDris2.service` and add to `[Unit]` an `Environmental=` entry but that would make me write that password in plain text and it's exactly what I'm trying to avoid.

Is what I'm trying to do possible using `pam-gnupg`?

I'll be very glad for help.

**Comment by cruegge** [comment]
So you basically need an unlocked gpg-agent when starting your systemd user services. One option might be to have the `session optional pam_gnupg.so` before the corresponding line for `pam_systemd.so`, so that the agent is started and unlocked before the user services.

The downside is that you do not manage the agent via systemd in that case. Moreover, IIUC, the `/run/user/$USER` directory is created by pam_systemd, and if it exists, gpg will search for the agent socket there. So to launch the agent first would require you to create the `/run/user` stuff manually even before pam_gnupg. This all sounds pretty hackish to me.

Another somewhat less hackish way might be to create a user service that waits for the agent to be unlocked, and have mpDris2 depend on that. Checking for unlocked keys can be done like

    echo keyinfo $KEYGRIP | gpg-connect-agent --no-autostart | head -n1 | cut -d' ' -f7

which prints `1` if the key is unlocked, `-` otherwise  (and probably fails if the agent is not running). I'm not exactly sure on the details, though. In particular, I *think* pam_systemd waits for the user services to be up before finishing. That's generally a good thing when putting `pam_gnupg.so` after `pam_systemd.so`, because it prevents a racing condition on who gets to start the agent, but in this case, it would lead to a deadlock.

I may have to check systemd's docs for that.

**Comment by doronbehar** [comment]
BTW, I ran across [this question](https://unix.stackexchange.com/q/287808/135796) and It seems to regard a similar issue as I'm. The difference is that the guy at UNIX Stackexchange **doesn't need an environmental variable** as an authentication method.

He said that he concluded that what he wants to achieve is not possible. Perhaps he wasn't aware of `pam-gnupg`? Do you think it provide an answer to his question?

**Comment by cruegge** [comment]
I'm not sure whether that is related. What they try to do looks a lot more complex than your case, and I do not really understand the precise reason why it is impossible.

I think the actual unlocking is not that hard to do; you could simply replace the mpDris2 `ExecStart` with an auxiliary wrapper script like

    #!/bin/bash
    export MPD_HOST=$(pass foo)
    exec command-to-launch-mpDris2

The more complex issue is the deadlock situation, because you want that service to run after pam_gnupg, which should however run after pam_systemd starts the agent. A way to handle it might be this (untested!):

1. The following script waits for your keys to become unlocked.

        #!/bin/bash
        cmds=$(perl -lne 'if (/^\s*([0-9A-Fa-f]{40})/) {print "keyinfo $1"}' < ~/.pam-gnupg)
        while echo "$cmds" \
                | gpg-connect-agent --no-autostart \
                | cut -d' ' -f7 \
                | grep -q '^-$'
        do
            sleep 1
        done


2. You can write a corresponding service like this

        [Unit]
        Description=Wait for gpg-agent to get unlocked
        Requires=sockets.target

        [Service]
        Type=oneshot
        ExecStart=/path/to/the/script/above.sh

     Let's call it `gpg-unlocked.service`. The dependency on `sockets.target` makes sure that the agent socket is available. If your gpg-agent is not started via socket activation, you need to adjust that line.


3. Other services like your wrapped mpDris2 may then depend on this service like

        [Unit]
        After=gpg-unlocked.service
        Wants=gpg-unlocked.service

        DefaultDependencies=no
        Requires=basic.target
        After=basic.target
        Conflicts=shutdown.target
        Before=shutdown.target
        (...)

    The final 5 lines make sure the service does not get an automatic `Before` relation to whatever target  `Wants` the service, as that will presumably be your `default.target`, which would cause the deadlock.

There are probably cleaner ways to do this, but my systemd-fu is a bit limited in this regard. Also, note thtat your session init should not assume mpDris2 to be available right away, as it will be started in parallel with your session.

Now that I think about it, a simpler way would be to just not `enable` mpDris2 at all, but start it using `systemctl --user` from your session init. That would prevent all racing conditions and deadlocks.

**Comment by doronbehar** [comment]
Haha, actually you bring up a good point. I guess that your last assertion provides just one of those arguments against systemd's complexity. In fact, that last suggestion you proposed is the one I thought of myself as a temporary setup for now - I just start `mpDris2` in `~/.xprofile`.

I guess I can keep it just like that for the meantime. I wonder if systemd will ever support non-plain-text authentication for commands in user services. Or perhaps GnuPG would write a systemd service like `gpg-unlocked` (but more reliable and resilient) just for these cases so that other services could depend on it like you suggested.
